# fly.toml app configuration file generated for happiness-backend-dev on 2023-11-27T10:22:58-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "happiness-backend-dev"
primary_region = "ewr"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
