"""revert user token update

Revision ID: 0a095327d61d
Revises: 13fc868bce68
Create Date: 2023-01-31 22:47:30.825163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a095327d61d'
down_revision = '13fc868bce68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_user')
    op.drop_table('setting')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('password_digest', sa.VARCHAR(), nullable=False),
    sa.Column('profile_picture', sa.VARCHAR(), nullable=False),
    sa.Column('session_token', sa.VARCHAR(), nullable=False),
    sa.Column('session_expiration', sa.DATETIME(), nullable=False),
    sa.Column('update_token', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('session_token'),
    sa.UniqueConstraint('update_token'),
    sa.UniqueConstraint('username')
    )
    op.create_table('setting',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('key', sa.VARCHAR(), nullable=False),
    sa.Column('value', sa.BOOLEAN(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_alembic_tmp_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('password_digest', sa.VARCHAR(), nullable=False),
    sa.Column('profile_picture', sa.VARCHAR(), nullable=False),
    sa.Column('update_token', sa.VARCHAR(), nullable=False),
    sa.Column('token', sa.VARCHAR(length=32), nullable=False),
    sa.Column('token_expiration', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('update_token'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
