"""user tokens refactor

Revision ID: 13fc868bce68
Revises: 976bda689a7a
Create Date: 2023-01-31 22:14:35.318316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13fc868bce68'
down_revision = '976bda689a7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('token_expiration', sa.DateTime(), nullable=False))
        batch_op.create_index(batch_op.f('ix_user_token'), ['token'], unique=True)
        batch_op.drop_column('session_token')
        batch_op.drop_column('session_expiration')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_expiration', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('session_token', sa.VARCHAR(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_user_token'))
        batch_op.drop_column('token_expiration')
        batch_op.drop_column('token')

    # ### end Alembic commands ###
