"""e2e test

Revision ID: 5a259ea01180
Revises: a164be6d68d2
Create Date: 2023-06-28 00:00:14.487226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a259ea01180'
down_revision = 'a164be6d68d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_key', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('secret', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('secret')
        batch_op.drop_column('encrypted_key')

    # ### end Alembic commands ###
