"""Added date created

Revision ID: 614dba985b58
Revises: 6f4aefb321e2
Create Date: 2023-04-23 00:00:08.436566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '614dba985b58'
down_revision = '6f4aefb321e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('created')

    # ### end Alembic commands ###
