"""Add communities and statistics

Revision ID: 620d8ef7fc21
Revises: c66650f95481
Create Date: 2023-07-23 16:52:52.823198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '620d8ef7fc21'
down_revision = 'c66650f95481'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enabled', sa.Boolean(), nullable=False))
        batch_op.alter_column('value',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_key', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('encrypted_key_recovery', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('encrypted_key_recovery')
        batch_op.drop_column('encrypted_key')

    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_column('enabled')

    op.drop_table('journal')
    # ### end Alembic commands ###
