"""add group tables

Revision ID: 63d75aae7325
Revises: 976bda689a7a
Create Date: 2023-01-29 13:57:05.417760

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '63d75aae7325'
down_revision = '976bda689a7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('group_users',
                    sa.Column('group_id', sa.Integer(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ondelete='cascade'),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_users')
    op.drop_table('group')
    # ### end Alembic commands ###
