"""add happiness table

Revision ID: 6f4aefb321e2
Revises: 63d75aae7325
Create Date: 2023-02-02 14:25:07.348567

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '6f4aefb321e2'
down_revision = '63d75aae7325'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('happiness',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('value', sa.Float(), nullable=True),
                    sa.Column('comment', sa.String(length=700), nullable=True),
                    sa.Column('timestamp', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('happiness')
    # ### end Alembic commands ###
