"""Add users and settings

Revision ID: 976bda689a7a
Revises: 
Create Date: 2023-01-25 21:50:56.143564

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '976bda689a7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('username', sa.String(), nullable=False),
                    sa.Column('password', sa.String(), nullable=False),
                    sa.Column('profile_picture', sa.String(), nullable=False),
                    sa.Column('session_token', sa.String(), nullable=False),
                    sa.Column('session_expiration', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('session_token'),
                    sa.UniqueConstraint('username')
                    )
    op.create_table('setting',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('key', sa.String(), nullable=False),
                    sa.Column('value', sa.Boolean(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('setting')
    op.drop_table('user')
    # ### end Alembic commands ###
