"""Move tokens to separate table

Revision ID: d4f640c3ff91
Revises: 614dba985b58
Create Date: 2023-05-28 21:06:27.536032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4f640c3ff91'
down_revision = '614dba985b58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_token', sa.String(), nullable=False),
    sa.Column('session_expiration', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('session_expiration')
        batch_op.drop_column('session_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_token', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('session_expiration', sa.DATETIME(), nullable=False))

    op.drop_table('token')
    # ### end Alembic commands ###
