name: Deploy
on:
  push:
    branches:
      - main
defaults:
  run:
    working-directory: happiness-backend
jobs:
  deploy:
    name: Dev Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to Fly
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
